### ISSUE TITLE
Integration issue with finatra at runtime

### ISSUE THREAD

**Issue by shravanak** [yahoo/maha#476]
Seeing this runtime exception when I pull in maha artifacts. 
Finatra uses netty 4.1.35.Final but somehow this class is getting pulled into the classpath from ning async-http-client as it pulls an older version of the DefaultChannelId class inside the jar.
https://github.com/impossibl/pgjdbc-ng/issues/332

Caused by: java.lang.NoSuchMethodError: io.netty.channel.DefaultChannelId.newInstance()Lio/netty/channel/DefaultChannelId;
	at io.netty.channel.AbstractChannel.newId(AbstractChannel.java:112)
	at io.netty.channel.AbstractChannel.<init>(AbstractChannel.java:84)
	at io.netty.bootstrap.FailedChannel.<init>(FailedChannel.java:33)
	at io.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:330)
	at io.netty.bootstrap.AbstractBootstrap.doBind(AbstractBootstrap.java:282)
	at io.netty.bootstrap.AbstractBootstrap.bind(AbstractBootstrap.java:278)
	at com.twitter.finagle.netty4.ListeningServerBuilder$$anon$1.<init>(ListeningServerBuilder.scala:172)
	at com.twitter.finagle.netty4.ListeningServerBuilder.bindWithBridge(ListeningServerBuilder.scala:78)
	at com.twitter.finagle.netty4.Netty4Listener.listen(Netty4Listener.scala:103)
	at com.twitter.finagle.server.StdStackServer.newListeningServer(StdStackServer.scala:82)
	at com.twitter.finagle.server.StdStackServer.newListeningServer$(StdStackServer.scala:69)
com.twitter.inject.server.EmbeddedTwitterServer.$anonfun$runNonExitingMain$2(EmbeddedTwitterServer.scala:623)
	... 26 more

**Comment by pranavbhole** [comment]
Can  you try excluding async-http-client from maha dependency. 
Best way would be we should upgrade ning client in the druid executor.
